/*
 * GroupDocs.Translation.ApiGateway.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GroupDocs.Translation.Cloud.Sdk.Client.OpenAPIDateConverter;

namespace GroupDocs.Translation.Cloud.Sdk.Model
{
    /// <summary>
    /// CloudHugoResponse
    /// </summary>
    [DataContract(Name = "CloudHugoResponse")]
    public partial class CloudHugoResponse : IEquatable<CloudHugoResponse>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public HttpStatusCode? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CloudHugoResponse" /> class.
        /// </summary>
        /// <param name="status">status.</param>
        /// <param name="message">If file was parsed correctly or text of error.</param>
        /// <param name="frontmatters">Structure of front matter syntax.</param>
        /// <param name="shortcodes">Structure of short code syntax.</param>
        public CloudHugoResponse(HttpStatusCode? status = default(HttpStatusCode?), string message = default(string), List<List<string>> frontmatters = default(List<List<string>>), List<List<string>> shortcodes = default(List<List<string>>))
        {
            this.Status = status;
            this.Message = message;
            this.Frontmatters = frontmatters;
            this.Shortcodes = shortcodes;
        }

        /// <summary>
        /// If file was parsed correctly or text of error
        /// </summary>
        /// <value>If file was parsed correctly or text of error</value>
        [DataMember(Name = "message", EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Structure of front matter syntax
        /// </summary>
        /// <value>Structure of front matter syntax</value>
        [DataMember(Name = "frontmatters", EmitDefaultValue = true)]
        public List<List<string>> Frontmatters { get; set; }

        /// <summary>
        /// Structure of short code syntax
        /// </summary>
        /// <value>Structure of short code syntax</value>
        [DataMember(Name = "shortcodes", EmitDefaultValue = true)]
        public List<List<string>> Shortcodes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CloudHugoResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Frontmatters: ").Append(Frontmatters).Append("\n");
            sb.Append("  Shortcodes: ").Append(Shortcodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CloudHugoResponse);
        }

        /// <summary>
        /// Returns true if CloudHugoResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CloudHugoResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CloudHugoResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.Frontmatters == input.Frontmatters ||
                    this.Frontmatters != null &&
                    input.Frontmatters != null &&
                    this.Frontmatters.SequenceEqual(input.Frontmatters)
                ) && 
                (
                    this.Shortcodes == input.Shortcodes ||
                    this.Shortcodes != null &&
                    input.Shortcodes != null &&
                    this.Shortcodes.SequenceEqual(input.Shortcodes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Status.GetHashCode();
                if (this.Message != null)
                {
                    hashCode = (hashCode * 59) + this.Message.GetHashCode();
                }
                if (this.Frontmatters != null)
                {
                    hashCode = (hashCode * 59) + this.Frontmatters.GetHashCode();
                }
                if (this.Shortcodes != null)
                {
                    hashCode = (hashCode * 59) + this.Shortcodes.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
