/*
 * GroupDocs.Translation.ApiGateway.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Translation.Api.Api;
using GroupDocs.Translation.Api.Model;
using GroupDocs.Translation.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Translation.Api.Test.Model
{
    /// <summary>
    ///  Class for testing CloudFileResponseWithDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CloudFileResponseWithDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CloudFileResponseWithDetails
        //private CloudFileResponseWithDetails instance;

        public CloudFileResponseWithDetailsTests()
        {
            // TODO uncomment below to create an instance of CloudFileResponseWithDetails
            //instance = new CloudFileResponseWithDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CloudFileResponseWithDetails
        /// </summary>
        [Fact]
        public void CloudFileResponseWithDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CloudFileResponseWithDetails
            //Assert.IsType<CloudFileResponseWithDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Urls'
        /// </summary>
        [Fact]
        public void UrlsTest()
        {
            // TODO unit test for the property 'Urls'
        }
        /// <summary>
        /// Test the property 'Scores'
        /// </summary>
        [Fact]
        public void ScoresTest()
        {
            // TODO unit test for the property 'Scores'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Request'
        /// </summary>
        [Fact]
        public void RequestTest()
        {
            // TODO unit test for the property 'Request'
        }

    }

}
