/*
 * GroupDocs.Translation.ApiGateway.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Translation.Api.Model;
using GroupDocs.Translation.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Translation.Api.Test.Model
{
    /// <summary>
    ///  Class for testing TextPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TextPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TextPostRequest
        //private TextPostRequest instance;

        public TextPostRequestTests()
        {
            // TODO uncomment below to create an instance of TextPostRequest
            //instance = new TextPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TextPostRequest
        /// </summary>
        [Fact]
        public void TextPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TextPostRequest
            //Assert.IsType<TextPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Targets'
        /// </summary>
        [Fact]
        public void TargetsTest()
        {
            // TODO unit test for the property 'Targets'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Texts'
        /// </summary>
        [Fact]
        public void TextsTest()
        {
            // TODO unit test for the property 'Texts'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Fact]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }

    }

}
