/*
 * GroupDocs.Translation.ApiGateway.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Translation.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AutoPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AutoPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AutoPostRequest
        //private AutoPostRequest instance;

        public AutoPostRequestTests()
        {
            // TODO uncomment below to create an instance of AutoPostRequest
            //instance = new AutoPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AutoPostRequest
        /// </summary>
        [Fact]
        public void AutoPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AutoPostRequest
            //Assert.IsType<AutoPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'OutputFormat'
        /// </summary>
        [Fact]
        public void OutputFormatTest()
        {
            // TODO unit test for the property 'OutputFormat'
        }
        /// <summary>
        /// Test the property 'Masters'
        /// </summary>
        [Fact]
        public void MastersTest()
        {
            // TODO unit test for the property 'Masters'
        }
        /// <summary>
        /// Test the property 'Formatting'
        /// </summary>
        [Fact]
        public void FormattingTest()
        {
            // TODO unit test for the property 'Formatting'
        }
        /// <summary>
        /// Test the property 'Route'
        /// </summary>
        [Fact]
        public void RouteTest()
        {
            // TODO unit test for the property 'Route'
        }
        /// <summary>
        /// Test the property 'Separator'
        /// </summary>
        [Fact]
        public void SeparatorTest()
        {
            // TODO unit test for the property 'Separator'
        }
        /// <summary>
        /// Test the property 'Elements'
        /// </summary>
        [Fact]
        public void ElementsTest()
        {
            // TODO unit test for the property 'Elements'
        }
        /// <summary>
        /// Test the property 'Ranges'
        /// </summary>
        [Fact]
        public void RangesTest()
        {
            // TODO unit test for the property 'Ranges'
        }
        /// <summary>
        /// Test the property 'ShortCodeList'
        /// </summary>
        [Fact]
        public void ShortCodeListTest()
        {
            // TODO unit test for the property 'ShortCodeList'
        }
        /// <summary>
        /// Test the property 'FrontMatterList'
        /// </summary>
        [Fact]
        public void FrontMatterListTest()
        {
            // TODO unit test for the property 'FrontMatterList'
        }
        /// <summary>
        /// Test the property 'SourceLanguage'
        /// </summary>
        [Fact]
        public void SourceLanguageTest()
        {
            // TODO unit test for the property 'SourceLanguage'
        }
        /// <summary>
        /// Test the property 'TargetLanguages'
        /// </summary>
        [Fact]
        public void TargetLanguagesTest()
        {
            // TODO unit test for the property 'TargetLanguages'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Fact]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'OriginalFileName'
        /// </summary>
        [Fact]
        public void OriginalFileNameTest()
        {
            // TODO unit test for the property 'OriginalFileName'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Fact]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'SavingMode'
        /// </summary>
        [Fact]
        public void SavingModeTest()
        {
            // TODO unit test for the property 'SavingMode'
        }

    }

}
