/*
 * GroupDocs.Translation.ApiGateway.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Translation.Cloud.Sdk.Model;
using GroupDocs.Translation.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Translation.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CloudHugoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CloudHugoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CloudHugoResponse
        //private CloudHugoResponse instance;

        public CloudHugoResponseTests()
        {
            // TODO uncomment below to create an instance of CloudHugoResponse
            //instance = new CloudHugoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CloudHugoResponse
        /// </summary>
        [Fact]
        public void CloudHugoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CloudHugoResponse
            //Assert.IsType<CloudHugoResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Frontmatters'
        /// </summary>
        [Fact]
        public void FrontmattersTest()
        {
            // TODO unit test for the property 'Frontmatters'
        }
        /// <summary>
        /// Test the property 'Shortcodes'
        /// </summary>
        [Fact]
        public void ShortcodesTest()
        {
            // TODO unit test for the property 'Shortcodes'
        }

    }

}
