/*
 * GroupDocs.Translation SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8.2
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Translation.Cloud.Sdk.Model;
using GroupDocs.Translation.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Translation.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing HugoRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HugoRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HugoRequest
        //private HugoRequest instance;

        public HugoRequestTests()
        {
            // TODO uncomment below to create an instance of HugoRequest
            //instance = new HugoRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HugoRequest
        /// </summary>
        [Fact]
        public void HugoRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" HugoRequest
            //Assert.IsType<HugoRequest>(instance);
        }


        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Fact]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
