/*
 * GroupDocs.Translation SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.8
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Translation.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ImageToTextPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImageToTextPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImageToTextPostRequest
        //private ImageToTextPostRequest instance;

        public ImageToTextPostRequestTests()
        {
            // TODO uncomment below to create an instance of ImageToTextPostRequest
            //instance = new ImageToTextPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImageToTextPostRequest
        /// </summary>
        [Fact]
        public void ImageToTextPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImageToTextPostRequest
            //Assert.IsType<ImageToTextPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Fact]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }

    }

}
