/*
 * GroupDocs.Translation SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.9.4
 * Contact: anton.perhunov@aspose.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Translation.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ImageToTextRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImageToTextRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImageToTextRequest
        //private ImageToTextRequest instance;

        public ImageToTextRequestTests()
        {
            // TODO uncomment below to create an instance of ImageToTextRequest
            //instance = new ImageToTextRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImageToTextRequest
        /// </summary>
        [Fact]
        public void ImageToTextRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImageToTextRequest
            //Assert.IsType<ImageToTextRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Targets'
        /// </summary>
        [Fact]
        public void TargetsTest()
        {
            // TODO unit test for the property 'Targets'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Fact]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Rotate'
        /// </summary>
        [Fact]
        public void RotateTest()
        {
            // TODO unit test for the property 'Rotate'
        }
        /// <summary>
        /// Test the property 'Ishandwritten'
        /// </summary>
        [Fact]
        public void IshandwrittenTest()
        {
            // TODO unit test for the property 'Ishandwritten'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Fact]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'Route'
        /// </summary>
        [Fact]
        public void RouteTest()
        {
            // TODO unit test for the property 'Route'
        }

    }

}
