/*
 * GroupDocs.Translation.ApiGateway.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Translation.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PdfFileRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PdfFileRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PdfFileRequest
        //private PdfFileRequest instance;

        public PdfFileRequestTests()
        {
            // TODO uncomment below to create an instance of PdfFileRequest
            //instance = new PdfFileRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PdfFileRequest
        /// </summary>
        [Fact]
        public void PdfFileRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PdfFileRequest
            //Assert.IsType<PdfFileRequest>(instance);
        }


        /// <summary>
        /// Test the property 'SourceLanguage'
        /// </summary>
        [Fact]
        public void SourceLanguageTest()
        {
            // TODO unit test for the property 'SourceLanguage'
        }
        /// <summary>
        /// Test the property 'TargetLanguages'
        /// </summary>
        [Fact]
        public void TargetLanguagesTest()
        {
            // TODO unit test for the property 'TargetLanguages'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Fact]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'OriginalFileName'
        /// </summary>
        [Fact]
        public void OriginalFileNameTest()
        {
            // TODO unit test for the property 'OriginalFileName'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Fact]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'SavingMode'
        /// </summary>
        [Fact]
        public void SavingModeTest()
        {
            // TODO unit test for the property 'SavingMode'
        }
        /// <summary>
        /// Test the property 'OutputFormat'
        /// </summary>
        [Fact]
        public void OutputFormatTest()
        {
            // TODO unit test for the property 'OutputFormat'
        }
        /// <summary>
        /// Test the property 'PreserveFormatting'
        /// </summary>
        [Fact]
        public void PreserveFormattingTest()
        {
            // TODO unit test for the property 'PreserveFormatting'
        }
        /// <summary>
        /// Test the property 'Pages'
        /// </summary>
        [Fact]
        public void PagesTest()
        {
            // TODO unit test for the property 'Pages'
        }

    }

}
