/*
 * GroupDocs.Translation.ApiGateway.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Translation.Cloud.Sdk.Model;
using GroupDocs.Translation.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Translation.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PresentationFileRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PresentationFileRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PresentationFileRequest
        //private PresentationFileRequest instance;

        public PresentationFileRequestTests()
        {
            // TODO uncomment below to create an instance of PresentationFileRequest
            //instance = new PresentationFileRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PresentationFileRequest
        /// </summary>
        [Fact]
        public void PresentationFileRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PresentationFileRequest
            //Assert.IsType<PresentationFileRequest>(instance);
        }


        /// <summary>
        /// Test the property 'SourceLanguage'
        /// </summary>
        [Fact]
        public void SourceLanguageTest()
        {
            // TODO unit test for the property 'SourceLanguage'
        }
        /// <summary>
        /// Test the property 'TargetLanguages'
        /// </summary>
        [Fact]
        public void TargetLanguagesTest()
        {
            // TODO unit test for the property 'TargetLanguages'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Fact]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'OriginalFileName'
        /// </summary>
        [Fact]
        public void OriginalFileNameTest()
        {
            // TODO unit test for the property 'OriginalFileName'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Fact]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'SavingMode'
        /// </summary>
        [Fact]
        public void SavingModeTest()
        {
            // TODO unit test for the property 'SavingMode'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'OutputFormat'
        /// </summary>
        [Fact]
        public void OutputFormatTest()
        {
            // TODO unit test for the property 'OutputFormat'
        }
        /// <summary>
        /// Test the property 'Masters'
        /// </summary>
        [Fact]
        public void MastersTest()
        {
            // TODO unit test for the property 'Masters'
        }
        /// <summary>
        /// Test the property 'Slides'
        /// </summary>
        [Fact]
        public void SlidesTest()
        {
            // TODO unit test for the property 'Slides'
        }

    }

}
