/*
 * GroupDocs.Translation.ApiGateway.Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupDocs.Translation.Cloud.Sdk.Model;
using GroupDocs.Translation.Cloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupDocs.Translation.Cloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing StringStringTuple
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StringStringTupleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StringStringTuple
        //private StringStringTuple instance;

        public StringStringTupleTests()
        {
            // TODO uncomment below to create an instance of StringStringTuple
            //instance = new StringStringTuple();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StringStringTuple
        /// </summary>
        [Fact]
        public void StringStringTupleInstanceTest()
        {
            // TODO uncomment below to test "IsType" StringStringTuple
            //Assert.IsType<StringStringTuple>(instance);
        }


        /// <summary>
        /// Test the property 'Item1'
        /// </summary>
        [Fact]
        public void Item1Test()
        {
            // TODO unit test for the property 'Item1'
        }
        /// <summary>
        /// Test the property 'Item2'
        /// </summary>
        [Fact]
        public void Item2Test()
        {
            // TODO unit test for the property 'Item2'
        }

    }

}
